### PR TITLE
Lee/heredoc

### LINKED ISSUE #13: Figure out adding SSH pub key to VM
Maybe use cloud-init?

### PR DESCRIPTION
**Pull request by VirtDev337**

### CODE REVIEW

**Review by thatoldplatitude — CHANGES_REQUESTED** [review]
We have a new key created & a cool new user too. But the last statement in our sh script isn't accounting for this. 
Also I foresee a problem keeping this script free to run to completion independent of user input. I think @stephenlauck  could shed better light on this. My assumption is: every instance is a new host, so tho our server would be accepting of these keys; client side woudn't always _know_ this new _host_ (see what I did there?)

**Comment by stephenlauck** [comment]
Yes, we are very much tying our delete to assumptions of our create. If we create the keys/vm, then we should delete the keys, vm and the cloud-init.yaml. Then we have a loop where our create is in a way "dependent" on our destroy.

**Comment by stephenlauck** [comment]
We'll rebase and fix conflicts on next session.

**Comment by stephenlauck** [comment]
next time, please rebase before merge.

**Pull request merged**
